service: mono-repo-sls-users

provider:
  name: aws
  runtime: nodejs8.10

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get
          cors: true
          
  new:
    handler: handler.hello
    events:
      - http:
          path: /new
          method: post
          cors: true


